# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-test-project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Install relevant packets (gnat and texinfo)
      run: sudo apt-get install gnat texinfo gdb gprbuild
    
    - name: Locate GDB version
      run: which gdb
      
    - name: Check GDB version
      run: gdb --version
    
    - name: Prepare some GDB command tests
      run: echo -e "help python\npython\nimport sys\nprint(\"Foo\")\nsys.exit(0)\nend\nq 25" > python_test.gdb
      
    - name: Check GDB supports python (exit code 25 means something went wrong in the python commands) otherwise exit code should be the 0 force un sys.exit(0)
      run: gdb --command=python_test.gdb --batch 
      
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: change directory
      run: pwd && ls -al && cd offsets_finder
      
      
    - name: build the test project
      run: gprbuild -p -P simple_offsets_finder.gpr

    # Runs a set of commands using the runners shell
    - name: Start a gdb session
      run: gdb --se=/exe/main --
